routes/web.php
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/home', function () {
    return view('admin.home.dashboard');
})->name('home')->middleware('redictrouter');

Route::get('', function () {
    return redirect('/login');
})->name('redictLogin');

Auth::routes();

//Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::prefix('roles')->name('roles.')->group(function(){
    Route::get('/', [\App\Http\Controllers\RoleController::class, 'index'])
        ->name('index')
        ->middleware('permission:role_view','auth');

    Route::get('/create', [\App\Http\Controllers\RoleController::class, 'create'])
        ->name('create')
        ->middleware('permission:role_create','auth');

    Route::post('/store', [\App\Http\Controllers\RoleController::class, 'store'])
        ->name('store')
        ->middleware('permission:role_store','auth');

    Route::get('/{id}', [\App\Http\Controllers\RoleController::class, 'show'])
        ->name('show')
        ->middleware('permission:role_show','auth');

    Route::get('/edit/{id}', [\App\Http\Controllers\RoleController::class, 'edit'])
        ->name('edit')
        ->middleware('permission:role_edit','auth');

    Route::put('/update/{id}', [\App\Http\Controllers\RoleController::class, 'update'])
        ->name('update')
        ->middleware('permission:role_update','auth');

    Route::delete('/delete/{id}', [\App\Http\Controllers\RoleController::class, 'destroy'])
        ->name('destroy')
        ->middleware('permission:role_delete','auth');
});

//-----------------------------User----------------------------------
Route::prefix('users')->name('users.')->group(function() {
    Route::get('/', [\App\Http\Controllers\UserController::class, 'index'])
        ->name('index')
        ->middleware('permission:user_view', 'auth');

    Route::get('/create', [\App\Http\Controllers\UserController::class, 'create'])
        ->name('create')
        ->middleware('permission:user_create', 'auth');

    Route::get('/{id}', [\App\Http\Controllers\UserController::class, 'show'])
        ->name('show')
        ->middleware('permission:user_show', 'auth');

    Route::delete('/delete/{id}', [\App\Http\Controllers\UserController::class, 'destroy'])
        ->name('destroy')
        ->middleware('permission:user_delete', 'auth');

    Route::get('/edit/{id}', [\App\Http\Controllers\UserController::class, 'edit'])
        ->name('edit')
        ->middleware('permission:user_edit', 'auth');

    Route::post('/store', [\App\Http\Controllers\UserController::class, 'store'])
        ->name('store')
        ->middleware('permission:user_store', 'auth');

    Route::put('/update/{id}', [\App\Http\Controllers\UserController::class, 'update'])
        ->name('update')
        ->middleware('permission:user_update', 'auth');
});
Route::post('/orders',[\App\Http\Controllers\UserController::class, 'orders'])
    ->name('orders');
Route::get('/vieworders', [\App\Http\Controllers\UserController::class , 'viewOrders'])
    ->name('vieworders')
    ->middleware( 'auth');
Route::put('/orders/{id}',[\App\Http\Controllers\UserController::class, 'UpdateOder'])
    ->name('orders.update');

Route::get('order/{id}',[HomeController::class,'show'])
    ->name('order.show')
    ->middleware('permission:product_show', 'auth');

// -------------------Category ----------------------------\\
Route::prefix('categories')->name('categories.')->group(function() {
    Route::get('categories', [\App\Http\Controllers\CategoryController::class, 'index'])
        ->name('index')
        ->middleware('permission:category_view', 'auth');

    Route::get('/create', [\App\Http\Controllers\CategoryController::class, 'create'])
        ->name('create')
        ->middleware('permission:category_create', 'auth');

    Route::post('/store', [\App\Http\Controllers\CategoryController::class, 'store'])
        ->name('store')
        ->middleware('permission:category_store', 'auth');

    Route::get('/edit/{id}', [\App\Http\Controllers\CategoryController::class, 'edit'])
        ->name('edit')
        ->middleware('permission:category_edit', 'auth');

    Route::put('/update/{id}', [\App\Http\Controllers\CategoryController::class, 'update'])
        ->name('update')
        ->middleware('permission:category_update', 'auth');

    Route::delete('/delete/{id}', [\App\Http\Controllers\CategoryController::class, 'destroy'])
        ->name('destroy')
        ->middleware('permission:category_delete', 'auth');

    Route::get('/list', [\App\Http\Controllers\CategoryController::class, 'list'])
        ->name('list')
        ->middleware('permission:category_view', 'auth');
});

// -------------------Product ----------------------------\\
Route::get('products',[\App\Http\Controllers\ProductController::class,'index'])
    ->name('products.index')
    ->middleware('permission:product_view', 'auth');

Route::get('prodcuts/{id}',[\App\Http\Controllers\ProductController::class,'show'])
    ->name('products.show')
    ->middleware('permission:product_show', 'auth');

Route::get('products/create',[\App\Http\Controllers\ProductController::class,'create'])
    ->name('products.create')
    ->middleware('permission:product_create', 'auth');

Route::get('prodcuts/edit/{id}',[\App\Http\Controllers\ProductController::class,'edit'])
    ->name('products.edit')
    ->middleware('permission:product_edit', 'auth');

Route::post('products/store',[\App\Http\Controllers\ProductController::class,'store'])
    ->name('products.store')
    ->middleware('permission:product_store', 'auth');

Route::put('prodcuts/update/{id}',[\App\Http\Controllers\ProductController::class,'update'])
    ->name('products.update')
    ->middleware('permission:product_update', 'auth');

Route::delete('products/delete/{id}',[\App\Http\Controllers\ProductController::class,'destroy'])
    ->name('products.destroy')
    ->middleware('permission:product_delete', 'auth');

Route::get('products/list',[\App\Http\Controllers\ProductController::class,'list'])
    ->name('products.list')
    ->middleware('permission:product_view', 'auth');
//Orders
Route::get('/admin/orders',[\App\Http\Controllers\OrderController::class,'index'])
    ->name('admin.orders')->middleware('auth');


// -------------------Post ----------------------------\\
Route::get('posts',[\App\Http\Controllers\PostController::class,'index'])
    ->name('posts.index')
    ->middleware( 'auth');

Route::get('posts/{id}',[\App\Http\Controllers\PostController::class,'show'])
    ->name('posts.show')
    ->middleware( 'auth');

Route::get('post/create', [\App\Http\Controllers\PostController::class, 'create'])
    ->name('post.create')
    ->middleware('auth');

Route::get('posts/edit/{id}',[\App\Http\Controllers\PostController::class,'edit'])
    ->name('posts.edit')
    ->middleware( 'auth');

Route::post('posts/store',[\App\Http\Controllers\PostController::class,'store'])
    ->name('posts.store')
    ->middleware( 'auth');

Route::put('posts/update/{id}',[\App\Http\Controllers\PostController::class,'update'])
    ->name('posts.update')
    ->middleware('permission:product_update', 'auth');

Route::delete('posts/delete/{id}',[\App\Http\Controllers\PostController::class,'destroy'])
    ->name('posts.destroy')
    ->middleware( 'auth');

// -------------------VoteComment ----------------------------\\
Route::get('/admin/vote',[\App\Http\Controllers\VoteController::class,'index'])
    ->name('admin.votes.index')
    ->middleware('auth');

// -------------------USER ----------------------------\\
// -------------------Home ----------------------------\\
Route::get('/',[\App\Http\Controllers\User\HomeController::class,'index'])
    ->name('home.index');

// -------------------UserProduct ----------------------------\\
Route::get('/user/product/detail/{id}',[ProductController::class,'show'])
    ->name('user.product.show');
Route::get('/user/product/list',[ProductController::class,'list'])
    ->name('user.product.list');
Route::get('/user/product/listCategory/{id}',[ProductController::class,'listCategory'])
    ->name('user.product.listCategory');

// -------------------UserVoteProduct ----------------------------\\
Route::post('/user/product/detail/{id}',[\App\Http\Controllers\User\VoteController::class,'store'])
    ->name('user.vote.store')->middleware('auth');
Route::delete('/user/product/delete/{id}',[\App\Http\Controllers\User\VoteController::class,'delete'])
    ->name('user.vote.delete')->middleware('auth');

// -------------------Cart ----------------------------\\
Route::get('cart/',[\App\Http\Controllers\User\CartController::class,'index'])
    ->name('cart.index')->middleware('auth');
Route::post('cart/add-to-cart/',[\App\Http\Controllers\User\CartController::class,'addCart'])
    ->name('cart.addCart')->middleware('auth');
Route::put('cart/update/{id}',[\App\Http\Controllers\User\CartController::class,'updateCart'])
    ->name('cart.updateCart')->middleware('auth');
Route::delete('cart/delete/{id}',[\App\Http\Controllers\User\CartController::class,'deleteCart'])
    ->name('cart.deleteCart')->middleware('auth');
Route::post('cart/add-to-cart/{id}',[\App\Http\Controllers\User\CartController::class,'addCartDetail'])
    ->name('cart.addCart.detail')->middleware('auth');

// -------------------post ----------------------------\\
Route::get('/user/posts/',[PostController::class,'index'])
    ->name('user.posts.index');
Route::get('/user/posts/detail/{id}',[PostController::class,'show'])
    ->name('user.posts.detail');

// -------------------Contact Us ----------------------------\\
Route::get('/user/contact/',[HomeController::class,'contact'])
    ->name('user.contact');

// -------------------About ----------------------------\\
Route::get('/user/about/',[HomeController::class,'about'])
    ->name('user.about');

Route::get('redirect/{driver}', [\App\Http\Controllers\Auth\LoginController::class,'redirectToProvider'])
    ->name('login.provider')

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    protected $table = 'categories';
    protected $fillable=[
        'parent_id',
        'name'
    ];

    public function products()
    {
        return $this->belongsToMany(Product::class, 'product_category', 'category_id', 'product_id');
    }

    public function post()
    {
        return $this->belongsTo(Post::class, 'category_id', 'id');
    }

    public function parent()
    {
        return $this->belongsTo(Category::class, 'parent_id', 'id');
    }

    public function childrens()
    {
        return $this->hasMany(Category::class, 'parent_id', 'id');
    }

    public function scopeWithName($query, $name)
    {
        return $name ? $query->where('name', 'like', '%' . $name . '%') : null;
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CategoryRequest;
use App\Services\CategoryService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\View;

class CategoryController extends Controller
{
    protected $categoryService;

    public function __construct(CategoryService $categoryService)
    {
        $this->categoryService = $categoryService;
    }

    public function index(Request $request)
    {
        $data = $this->categoryService->search($request);

        return view('admin.categories.list', compact('data'));
    }

//    public function list(Request $request)
//    {
//        $data = $this->categoryService->search($request);
//
//        return view('admin.categories.list', compact('data'));
//    }

    public function create()
    {
        return view('admin.categories.create');
    }

    public function store(CategoryRequest $request)
    {
        $this->categoryService->create($request);
        return redirect()->route('categories.index')->with('message', 'Category Create successfully');
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $data = $this->categoryService->find($id);
        return view('admin.categories.edit', compact('data'));
    }

    public function update(CategoryRequest $request, $id)
    {
        $this->categoryService->update($request, $id);
        return redirect()->route('categories.index')->with('message', 'Category updated successfully');
    }

    public function destroy($id)
    {
        $this->categoryService->delete($id);
        return $this->sendSuccessResponse('', 'Delete product success', $status = 200);
    }
}

resources/views/admin/categories/category1.blade.php
@extends('admin.layouts.app')

{{--@section('title', 'Dashboard')--}}
@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper" id="something">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Categories</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{route('home')}}">Home</a></li>
                            <li class="breadcrumb-item active">Categories</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card-header clearfix">
                            @hasPermission('category_create')
                            <button type="button" class="btn btn-primary" id="btn-add-category"  data-bs-toggle="modal"
                                    data-bs-target="#CreateCategoryModal">
                                <i class="fas fa-plus"></i> &nbsp; Add Category
                            </button>
                            <button type="button" class="btn btn-primary" id="btn-add-category"  data-bs-toggle="modal"
                                    data-bs-target="#CreateCategoryModal">
                                <i class="fas fa-plus"></i> &nbsp; List Category
                            </button>
                            @endhasPermission
                        </div>

                        @if ($message = Session::get('success'))
                            <div class="alert alert-success">
                                <p class="text-white">{{ $message }}</p>
                            </div>
                        @endif

                        <div class="card">
                            <div class="card-header" style="padding-left: 20%; background: #f3f8fa">
                                <div class="col-md-10" style="margin-top: 5px; margin-bottom: 10px">
                                    <form method="GET" class="m-md-3 d-flex" style="padding-right: 10%" id="search">
                                        <select name="parent_id" id="parent_id"  class=" form-control col-md-2 mr-2"
                                                aria-label="Default select example" style="width: 30%">
                                            <option value=" " selected>Parent Name</option>
                                            {{--                                            @foreach($categories as $category)--}}
                                            {{--                                                <option value="{{$parent->id}}">{{$parentId->name}}</option>--}}
                                            {{--                                            @endforeach--}}
                                            @foreach($categories as $key => $category)
                                                @if($category->parent_id == null)
                                                    <option value="{{$category->id}}">
                                                        {{$category->name}}
                                                    </option>
                                                @endif
                                            @endforeach

                                        </select>
                                        <input type="search" name="name" id="name" value="{{ request('name') }}"
                                               class="form-control"
                                               placeholder="name ...">
                                    </form>
                                </div>
                            </div>
                            <div id="list" data-action="{{route('categories.list')}}">
                            </div>
                        </div>
                        <!-- /.card -->
                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->


    <!-- Create Modal -->
    <div class="modal" id="CreateCategoryModal">
        <div class="modal-dialog">
            <div class="modal-content">

                <!-- Modal Header -->
                <div class="modal-header">
                    <h4 class="modal-title">Create Category</h4>
                    <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                </div>

                <form id="CreateCategoryForm" method="POST" enctype="multipart/form-data" data-action="{{route('categories.store')}}">
                    @csrf
                    <div class="modal-body">
                        <ul class="alert alert-warning d-none" id="_error_create"></ul>
                        <div class="form-group mb-3">
                            <label>Name</label>
                            <input type="text" class="form-control" id="nameCreate" name="name">
                            <span class="text-danger name_error_create"></span>
                        </div>
                        <div class="form-group mb-3">
                            <label>Parent Category</label>
                            <select class="form-control" id="parentIdCreate" name="parent_id">
                                <option value="">Chọn danh mục</option>
                                @foreach($categories as $parentId)
                                    <option value="{{$parentId->id}}">{{$parentId->name}}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"
                        >Close
                        </button>
                        <button type="button" class="btn btn-primary btn-create" id="btn-store"
                        >Save
                        </button>
                    </div>
                </form>

            </div>
        </div>
    </div>

    <!-- Edit Modal -->
    <div class="modal" id="EditCategoryModal">
        <div class="modal-dialog">
            <div class="modal-content">

                <!-- Modal Header -->
                <div class="modal-header">
                    <h4 class="modal-title">Update Category</h4>
                    <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                </div>

                <div id="edit"></div>

            </div>
        </div>
    </div>

@endsection

resources/views/admin/categories/create.blade.php
@extends('admin.layouts.app')

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Categories</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{route('home')}}">Home</a></li>
                            <li class="breadcrumb-item"><a href="{{route('products.index')}}">Categories</a></li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <!-- left column -->
                    <div class="col">
                        <!-- general form elements -->
                        <div class="card card-primary">
                            <div class="card-header">
                                <h3 class="card-title">Add Categories</h3>
                            </div>
                            <!-- /.card-header -->
                            <!-- form start -->
                            <form action="{{route('categories.store')}}" enctype="multipart/form-data"  method="POST">
                                @csrf
                                <div class="card-body">
                                    <div class="form-group">
                                        <label class="form-label">Name</label>
                                        <input name="name" type="text" class="form-control" placeholder="Name...">
                                        <p>
                                        @error('name')
                                        <div class="link-danger">{{ $message }}</div>
                                        @enderror
                                        </p>
                                    </div>
                                </div>
                                <div class="card-body">
                                    <div class="form-group">
                                        <label class="form-label">Parent Name</label>
                                        <select name="parent_id" type="text" class="form-control">
                                            <option value=""></option>
                                            @foreach($categories as $key => $category)
                                                @if($category->parent_id == null)
                                                    <option value="{{$category->id}}">{{$category->name}}</option>
                                                @endif
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                                <!-- /.card-body -->
                                <div class="card-footer">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                </div>
                            </form>
                        </div>
                        <!-- /.card -->

                    </div>
                    <!--/.col (left) -->
                    <!-- right column -->
                    <!--/.col (right) -->
                </div>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
@endsection

resources/views/admin/categories/detail.blade.php
<div class="modal fade" id="show">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Detail</h4>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            </div>
            <div class="modal-body">
                <h2>Thông tin sinh viên:</h2>
                id: <h1 id="id"></h1>
                Tên: <h1 id="name"></h1>
                parent_id <h1 id="parent_id"></h1>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

resources/views/admin/categories/edit.blade.php
@extends('admin.layouts.app')

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Categories</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{route('home')}}">Home</a></li>
                            <li class="breadcrumb-item"><a href="{{route('products.index')}}">Categories</a></li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <!-- left column -->
                    <div class="col">
                        <!-- general form elements -->
                        <div class="card card-primary">
                            <div class="card-header">
                                <h3 class="card-title">Add Categories</h3>
                            </div>
                            <!-- /.card-header -->
                            <!-- form start -->
                            <form action="{{route('categories.update',$data->id)}}" enctype="multipart/form-data"  method="POST">
                                @csrf
                                @method('PUT')
                                <div class="card-body">
                                    <div class="form-group">
                                        <label class="form-label">Name</label>
                                        <input name="name" type="text" class="form-control" value="{{$data->name}}">
                                        <p>
                                        @error('name')
                                        <div class="link-danger">{{ $message }}</div>
                                        @enderror
                                        </p>
                                    </div>
                                </div>
                                <div class="card-body">
                                    <div class="form-group">
                                        <label class="form-label">Parent Name</label>
                                        <select name="parent_id" type="text" class="form-control">
                                            <option value=""></option>
                                            @foreach($categories as $key => $category)
                                                @if($category->parent_id == null)
                                                    <option value="{{$category->id}}">{{$category->name}}</option>
                                                @endif
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                                <!-- /.card-body -->
                                <div class="card-footer">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                </div>
                            </form>
                        </div>
                        <!-- /.card -->

                    </div>
                    <!--/.col (left) -->
                    <!-- right column -->
                    <!--/.col (right) -->
                </div>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
@endsection

resources/views/admin/categories/listCate.blade.php
@extends('admin.layouts.app')
@php
    $stt = (($_GET['page'] ?? 1) - 1) * 5;
@endphp
@section('content')
    <div class="content-wrapper" id="something">
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Category</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{route('home')}}">Home</a></li>
                            <li class="breadcrumb-item active">Category</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>
        <div id="list" data-action="{{route('categories.list')}}">
            <div class="card-body">
                <table id="example2" class="table table-bordered table-hover">
                    <thead>
                    <tr>
                        <th style="width: 5%">ID</th>
                        <th>Name</th>
                        <th>Parent Name</th>
                        <th style="width: 15%">Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($data as $category)
                        <tr id="xid{{$category->id}}">
                            <td>{{++$stt}}</td>
                            <td>{{$category->name}}</td>
                            <td>{{ $category->parent->name ?? ""}}</td>
                            <td>
                                @hasPermission('category_edit')
                                <a href="{{route('categories.edit', $category->id)}}"
                                   class="badge bg-success"><i class="fas fa-edit"></i></a>
                                @endhasPermission
                                <a>
                                    <button data-id="{{$category->id}}"
                                            class=" deleteCategory badge bg-danger btn-delete">
                                        <i class="fas fa-trash"></i>
                                    </button>
                                </a>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
                <p>
                    {{$data->appends(request()->all())->Links()}}
                </p>
            </div>
            <!-- /.card-body -->
        </div>
    </div>
@endsection